runtime: python27
env: flex
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_dir: build
- url: /(.*)
  static_files: build/\1
  upload: build/(.*)