steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['build']
  - name: gcr.io/cloud-builders/gsutil
    args: ['rsync', '-R', 'build', 'gs://getbus.wxuan.co']